// Agri_Bloom — StandardScaler parameters for ESP32 normalisation
// Auto-generated by Agri_Bloom_Stage1_ML_Training.ipynb
// Features: soil_moisture, light_level, temperature, humidity

#ifndef AGRI_BLOOM_SCALER_H
#define AGRI_BLOOM_SCALER_H

// Use these as initial means/stds for Welford online learner
const float SENSOR_MEANS[4] = { 57.425648f, 2372.902714f, 23.950813f, 66.196329f };
const float SENSOR_STDS[4]  = { 21.154941f, 1561.420875f, 5.628762f, 20.181298f  };

// Class label order (matches OHE column order used during training)
const char* DIAGNOSIS_LABELS[7] = {
    "Fungal_Risk",
    "Healthy",
    "Heat_Stress",
    "Light_Deficiency",
    "Nutrient_Deficiency",
    "Root_Rot_Risk",
    "Water_Stress",
};

#endif // AGRI_BLOOM_SCALER_H
